version: '3.9'
services:
  db:
    restart: unless-stopped
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  core:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - logs:/app/logs
    depends_on:
      - db
    env_file: .env
    environment:
      - POSTGRES_HOST=db

volumes:
  logs: {}
  db-data: {}
